name: CI/CD Docker hub frontserver workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sukyu0919/nike_frontserver
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ec2-13-125-126-92.ap-northeast-2.compute.amazonaws.com
        username: ${{ secrets.AWS_USERNAME }}
        password: ${{ secrets.AWS_PASSWORD }}
        script: |
          docker stop nike-frontserver
          docker rm -fv nike-frontserver
          docker rmi sukyu0919/nike_frontserver:latest
          docker pull sukyu0919/nike_frontserver
          docker run -d --name nike_frontserver -p 80:80 sukyu0919/nike_frontserver
